#!/usr/bin/env python3
"""Regenerate docs/tool-catalog.md by introspecting registered FastMCP tools.

Usage (from repo root):
    python scripts/generate_tool_catalog.py

Prints a diff-friendly Markdown table of all registered tools with their
input schema and docstring. The full narrative catalog in docs/tool-catalog.md
is hand-maintained; this script is a quick sanity-check that detects new or
removed tools.
"""

from __future__ import annotations

import asyncio
import json
import sys
from pathlib import Path

# Make the src packages importable without installing
sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

import allplan_mcp_server.tools  # noqa: F401 — registers all @mcp.tool decorators
from allplan_mcp_server.server import mcp


async def _collect() -> list[dict]:
    tools = await mcp.list_tools()
    return [
        {
            "name": t.name,
            "description": (t.description or "").splitlines()[0].strip(),
            "params": sorted(t.inputSchema.get("properties", {}).keys()),
            "required": sorted(t.inputSchema.get("required", [])),
        }
        for t in sorted(tools, key=lambda t: t.name)
    ]


def _render(tools: list[dict]) -> str:
    lines = [
        "# Tool Catalog (auto-generated)",
        "",
        f"Total: {len(tools)} tools.",
        "",
        "| Tool | Description | Required params |",
        "|---|---|---|",
    ]
    for t in tools:
        req = ", ".join(f"`{p}`" for p in t["required"]) or "—"
        lines.append(f"| `{t['name']}` | {t['description']} | {req} |")
    lines.append("")
    lines.append("*Generated by `scripts/generate_tool_catalog.py`. "
                 "Edit `docs/tool-catalog.md` for the full narrative catalog.*")
    return "\n".join(lines)


def main() -> None:
    try:
        tools = asyncio.run(_collect())
    except Exception as exc:
        print(f"ERROR collecting tools: {exc}", file=sys.stderr)
        print("Ensure 'uv sync' has been run and FastMCP is importable.", file=sys.stderr)
        sys.exit(1)

    catalog = _render(tools)

    out_path = Path(__file__).resolve().parent.parent / "docs" / "tool-catalog-generated.md"
    out_path.write_text(catalog, encoding="utf-8")
    print(f"Written {len(tools)} tools to {out_path}")
    print()

    # Also print to stdout for quick review
    print(catalog)


if __name__ == "__main__":
    main()
